py -m pip install nvidia-cuda-runtime-cu11
py -m pip install  nvidia-cuda-cupti-cu11
py -m pip install  nvidia-cuda-nvcc-cu11
py -m pip install  nvidia-nvml-dev-cu11
py -m pip install  nvidia-cuda-nvrtc-cu11
py -m pip install  nvidia-nvtx-cu11
py -m pip install  nvidia-cuda-sanitizer-api-cu11
py -m pip install  nvidia-cublas-cu11
py -m pip install  nvidia-cufft-cu11
py -m pip install  nvidia-curand-cu11
py -m pip install  nvidia-cusolver-cu11
py -m pip install  nvidia-cusparse-cu11
py -m pip install  nvidia-npp-cu11
py -m pip install  nvidia-nvjpeg-cu11
py -m pip install  nvidia-nvml-dev-cu114
py -m pip install  nvidia-cuda-nvcc-cu114
py -m pip install  nvidia-cuda-runtime-cu114
py -m pip install  nvidia-cuda-cupti-cu114
py -m pip install  nvidia-cublas-cu114
py -m pip install  nvidia-cuda-sanitizer-api-cu114
py -m pip install  nvidia-nvtx-cu114
py -m pip install  nvidia-cuda-nvrtc-cu114
py -m pip install  nvidia-npp-cu114
py -m pip install  nvidia-cusparse-cu114
py -m pip install  nvidia-cusolver-cu114
py -m pip install  nvidia-curand-cu114
py -m pip install  nvidia-cufft-cu114
py -m pip install  nvidia-nvjpeg-cu114